### ISSUE TITLE
Question regarding >51 entries in root dir

### ISSUE THREAD

**Issue by bobbimanners** [ProDOS-8/ProDOS8-Testing#15]
Not a bug report - just a question

BUG

2.5
## Description

What happens if I create more than 51 entries in the root directory and then boot an older ProDOS?  Just want to know before I accidentally do it.  I have nearly 50 entries at the moment.

### ProDOS8 version:
2.5.0a3

**Comment by JohnMBrooks** [comment]
By default, ProDOS 2.5.0 will not expand the root directory past 51 entries, since if PRODOS was file 52+ in the list, the old ProDOS boot blocks would not be able to find it and the disk would not be able to boot.

I plan to have a P8 Admin tool which will install the new boot blocks and set the root directory attribute so the root directory can expand past 51 files. I can tell you how to set this attribute manually if you would like to test >51 files in the root dir.

**Comment by bobbimanners** [comment]
Sure I am happy to test this.

**Comment by JohnMBrooks** [comment]
ProDOS 2.5 replaces a 'reserved, value $00' byte at offset $14 in block two with a 'root block len' byte.

If block2+$14 is $00, then the root directory remains limited to 51 files. If this byte is $04, then ProDOS 2.5 will know that the root dir is 4 blocks long and can grow as needed.

You can use Block Warden from Prosel 4.0 to manually read block 2, change offset $14 to $04, then write block 2 which will then enable >51 files in the root directory.

It is also a good idea to use Block Warden to replace blocks 0 & 1 of the target device with the new boot blocks from the ProDOS 2.5.0 floppy. The new boot blocks can find the PRODOS file even in a very large root directory with >51 files.
 
Eventually there will be an admin tool to do these steps for users.

**Comment by bobbimanners** [comment]
I will give this a whirl on a spare partition somewhere :)

My root directory is 46 entries already, so this would potentially be useful.

**Comment by bobbimanners** [comment]
If I have a ProDOS filesystem with >51 entries, what will older ProDOS (say 2.4.2) make of it?  Or is it more about the boot blocks being able to find PRODOS?

**Comment by JohnMBrooks** [comment]
Apps on older versions of ProDOS will see >51 files if they open and read the entire root directory as a file, but if they ask for the length of the root directory, older prodos versions will return 4 blocks (51 files).

And older ProDOS versions will not expand the root directory beyond it's current number of blocks.

It's probably safest to test using a ram disk or floppy disk.

**Comment by bobbimanners** [comment]
I have a few scratch partitions, but maybe a separate device would be safer still.  That is why I have backups though :)

**Comment by bobbimanners** [comment]
I gave this a quick try with /RAM but without much success.  Maybe I am messing something up.

First a baseline test.  I have a little Applesoft program like this:
```
10 D$=CHR$(4)
15 PRINT D$;"PREFIX /RAM"
20 FOR I=1 TO 255
30 PRINT D$;"CREATE A";I
40 PRINT I
50 NEXT
```
Running this creates A1 through A21 and then stops with DIRECTORY FULL.  So far so good.

Then using Blockwarden, I modify offset $14 in block 2 of device 3,2 (/RAM) to 04.  After this performing a catalog of /RAM shows a partial corrupt catalog of another volume (showing the volume name and the first few entries from my first HDD volume in slot 7, drive 1 (/H1)).

Reboot and everything goes back to normal. so it is just a corrupt RAM-disk directory.

What am I missing?  I guess I am modifying the wrong byte somehow.

**Comment by JohnMBrooks** [comment]
The aux /RAM root dir is nonstandard with only 1 root dir block. Try changing /RAM Blk2+$14 to $01.

**Comment by bobbimanners** [comment]
Tried it with a good old 143K Disk ][ floppy .. same result.  Corrupt directory whether listed using CAT or Bitsy Bye.  I must have the wrong offset or wrong block?

**Comment by bobbimanners** [comment]
Let me try $01 as the value.

**Comment by bobbimanners** [comment]
OK, I tried the value $01 and that is an improvement in the sense that I no longer get a directory with corrupt garbage entries, like I did with $04.  However instead I get the directory of my first HDD volume.  This is with a floppy in S6D1 and HDD partition in S7D1.  After changing offset $14 of block 2 of the floppy to value $01, and rebooting for good measure, I get:

```
]cat,s7,d1

/H1                                    

 NAME           TYPE  BLOCKS  MODIFIED 

 PRODOS          SYS      34  25Jul2011
 QUIT.SYSTEM     SYS       1  15Sep2016
 BASIC.SYSTEM    SYS      21  21Jun2010
 SHELL.SYSTEM    SYS      54  27Jun1986
 PROSEL.SYSTEM   SYS       1   1Apr1988
 PROFILE         TXT       1  17Aug2019
 PROSEL          BIN      13  23Aug1989
 A2DESKTOP.1.1   DIR       1  21Aug2019
 ADTPRO.2.0.3    DIR       1  21Aug2019
 APPLE2PI.1.6    DIR       1  27Aug2019
 APPLE.DEMOS     DIR       1  21Aug2019
 APPLE.UTILS     DIR       1  21Aug2019
 APPLESOFT       DIR       2  21Aug2019
 APPLEWORKS.1.3  DIR       1  21Aug2019
 APPLEWORKS.2.1  DIR       1  21Aug2019
 APPLEWORKS.3.0  DIR       2  26Aug2019
 APPLEWORKS.4.3  DIR       3  27Aug2019
 APPLEWORKS.5.1  DIR       3  21Aug2019
 APPLEWORKS.DATA DIR       1  24Aug2019
 APPLEWRITER.2.0 DIR       2  21Aug2019
 AZTEC.C65.3.2   DIR       1  21Aug2019
 COMMWORKS.1.3   DIR       1  21Aug2019
 DOS.MASTER      DIR       3  21Mar1988
 COPY2PLUS.8.4   DIR       1  21Aug2019
 COPY2PLUS.9.1   DIR       2  21Aug2019
 EIGHTBALL       DIR       1  21Aug2019
 IIE.DIAG.2.1    DIR       1  21Aug2019
 KYAN.PASCAL     DIR       1  21Aug2019
 MERLIN8.2.58    DIR       1  21Aug2019
 MICRODRIVE      DIR       1  21Aug2019
 MISC.UTILS      DIR       1  30Mar2004
 MOUSEDESK.1.02  DIR       1  21Aug2019
 PROCMD.2.21     DIR       2   5Sep1991
 PRODOS.2.4.1    DIR       1  21Aug2019
 PRODOS.2.4.2    DIR       2  21Aug2019
 PRODOS.2.5.0A2  DIR       1  21Aug2019
 PRODOS.2.5.0A3  DIR       1  19Aug2019
 PROG.WRITER.2.0 DIR       1   5Sep1991
 PROSEL.4.0      DIR       2  21Aug2019
 PROTERM.3.1     DIR       2  21Aug2019
 QUICKEN         DIR       2  21Aug2019
 SHRINKIT.3.4    DIR       1  21Aug2019
 SUPERCALC3A.1.1 DIR       3  30Sep1985
 VDRIVE.2.0.3    DIR       1  21Aug2019
 VISICALC.ADV    DIR       2  21Aug2019
 WORDPERFECT.1.1 DIR       2  27Aug2019

BLOCKS FREE:48732     BLOCKS USED:16803


]
]cat,s6,d1

/H1                                    

 NAME           TYPE  BLOCKS  MODIFIED 

 PRODOS          SYS      34  25Jul2011
 QUIT.SYSTEM     SYS       1  15Sep2016
 BASIC.SYSTEM    SYS      21  21Jun2010
 SHELL.SYSTEM    SYS      54  27Jun1986
 PROSEL.SYSTEM   SYS       1   1Apr1988
 PROFILE         TXT       1  17Aug2019
 PROSEL          BIN      13  23Aug1989
 A2DESKTOP.1.1   DIR       1  21Aug2019
 ADTPRO.2.0.3    DIR       1  21Aug2019
 APPLE2PI.1.6    DIR       1  27Aug2019
 APPLE.DEMOS     DIR       1  21Aug2019
 APPLE.UTILS     DIR       1  21Aug2019

BLOCKS FREE:  273     BLOCKS USED:65262


]

```

**Comment by bobbimanners** [comment]
Floppy was freshly formatted in CAT.DOCTOR by the way.  Volume name was NEWDISK.

**Comment by bobbimanners** [comment]
"Blocks used" looks a bit fishy on the floppy disk :)

**Comment by bobbimanners** [comment]
I did a bit more testing with 2.5.0a3 tonight, using a Disk ][ floppy.  I tried to be systematic, because these symptoms seem odd to me.

**Baseline Sanity Test**

1. Formatted floppy in CAT.DOCTOR.  Volume name is /NEWDISK.
2. Ran my BASIC program to create directories.  I was able to create 51 directories on S6D1 then I get 'DIRECTORY FULL'.
3. CAT,S1,D1 and all my 51 directories are present and correct.

**First Attempt at Modifying Block 2**

1. Formatted the floppy afresh as /NEWDISK again.
2. Using BLOCK.WARDEN I modified block 2, offset $14 to value 4.
3. CAT,S1,D1 shows 12 entries of a completely different volume (/H1) as described yesterday.
4. Scratch head

**Second Attempt**

I wondered how things would look if I put some files on the disk before modifying block 2.

1. Formatted floppy in CAT.DOCTOR.  Volume name is /NEWDISK.
2. Ran my BASIC program to create directories.  I was able to create 51 directories on S6D1 then I get 'DIRECTORY FULL'.
3. CAT,S1,D1 and all my 51 directories are present and correct.
4. Using BLOCK.WARDEN I modified block 2, offset $14 to value 4.
5. CAT,S1,D1 shows a corrupt directory with the first 12 entries from /H1 but the remaining entries are the directories my BASIC program created:

```
]cat,s6,d1

/H1                                    

 NAME           TYPE  BLOCKS  MODIFIED 

 PRODOS          SYS      34  25Jul2011
 QUIT.SYSTEM     SYS       1  15Sep2016
 BASIC.SYSTEM    SYS      21  21Jun2010
 SHELL.SYSTEM    SYS      54  27Jun1986
 PROSEL.SYSTEM   SYS       1   1Apr1988
 PROFILE         TXT       1  17Aug2019
 PROSEL          BIN      13  23Aug1989
 A2DESKTOP.1.1   DIR       1  21Aug2019
 ADTPRO.2.0.3    DIR       1  21Aug2019
 APPLE2PI.1.6    DIR       1  27Aug2019
 APPLE.DEMOS     DIR       1  21Aug2019
 APPLE.UTILS     DIR       1  21Aug2019
 A13             DIR       1  <NO DATE>
 A14             DIR       1  <NO DATE>
 A15             DIR       1  <NO DATE>
 A16             DIR       1  <NO DATE>
 A17             DIR       1  <NO DATE>
 A18             DIR       1  <NO DATE>
 A19             DIR       1  <NO DATE>
 A20             DIR       1  <NO DATE>
 A21             DIR       1  <NO DATE>
 A22             DIR       1  <NO DATE>
 A23             DIR       1  <NO DATE>
 A24             DIR       1  <NO DATE>
 A25             DIR       1  <NO DATE>
 A26             DIR       1  <NO DATE>
 A27             DIR       1  <NO DATE>
 A28             DIR       1  <NO DATE>
 A29             DIR       1  <NO DATE>
 A30             DIR       1  <NO DATE>
 A31             DIR       1  <NO DATE>
 A32             DIR       1  <NO DATE>
 A33             DIR       1  <NO DATE>
 A34             DIR       1  <NO DATE>
 A35             DIR       1  <NO DATE>
 A36             DIR       1  <NO DATE>
 A37             DIR       1  <NO DATE>
 A38             DIR       1  <NO DATE>
 A39             DIR       1  <NO DATE>
 A40             DIR       1  <NO DATE>
 A41             DIR       1  <NO DATE>
 A42             DIR       1  <NO DATE>
 A43             DIR       1  <NO DATE>
 A44             DIR       1  <NO DATE>
 A45             DIR       1  <NO DATE>
 A46             DIR       1  <NO DATE>
 A47             DIR       1  <NO DATE>
 A48             DIR       1  <NO DATE>
 A49             DIR       1  <NO DATE>
 A50             DIR       1  <NO DATE>
 A51             DIR       1  <NO DATE>

BLOCKS FREE:  989     BLOCKS USED:64546

```
I am not sure if that helps at all, but thought I would share my observations.

**Comment by JohnMBrooks** [comment]
Fixed in 2.5.0a4.

**Comment by bobbimanners** [comment]
Awesome - fast work John!!  When is alpha4 expected to hit the streets?  Can't wait to give it a try!

**Comment by JohnMBrooks** [comment]
a4 is here:

https://drive.google.com/open?id=1DNFFd2BLIXL3krPbGWvfu8E0m9fwZiRP

**Comment by bobbimanners** [comment]
Still happening for me with 2.5.0a4.  This is using a 143K Disk II floppy.  I don't think there is any additional info to report.  I can reproduce this as described above.

**Comment by JohnMBrooks** [comment]
I am unable to repro any problems on either /RAM or a CD /NEWDISK.

Here are latest 2.5.0a4 and test disk with Blk2+$14 == $04.

https://drive.google.com/open?id=1DNFFd2BLIXL3krPbGWvfu8E0m9fwZiRP
https://drive.google.com/open?id=1NRF_RHI0Zh-9tsvrIH2NT8kvTMoTh2aW

**Comment by bobbimanners** [comment]
This is very strange.  I am wondering if I am messing up with BLOCK.WARDEN somehow, but it seems pretty clear so I don't think I am frobbing the wrong byte.

I will have a play with your test image this week - it will have to be on emulator rather than the real hardware though.

**Comment by bobbimanners** [comment]
I guess I must be messing up with BLOCK.WARDEN somehow, although I thought it was unambiguous.

Using your test image and 2.5.0a4 release 2, I can create more that 51 entries on my 143K floppy.  My BASIC program keeps creating directories in the top level of the disk.  I can create 252 directories until I get DISK FULL (280 blocks used).

I am back home so the testing was performed with real hardware.  I will continue to investigate this a bit and see if I can work out how I was messing up ...

EDIT: I worked out where I was going wrong with BLOCK.WARDEN -- when I type 'C' to change drives and enter the slot and drive (6,1) BLOCK.WARDEN starts out showing block 2, but you have to press 'R' to actually read the block.  This is a bit confusing since it loads the initial block when it is started but then behaves differently when you switch drives.  I assume this is to allow copying a block from one drive to another (very handy) but the UI got the better of me ;)

**Comment by bobbimanners** [comment]
Now I know how to drive BLOCK.WARDEN more competently, I successfully changed block 2 offset $14 of my floppy to value $04.  I can successfully create more than 51 entries on the diskette.  It takes quite a while on such a slow device as the Disk II, but creating directories seems to be a very seeky activity.  There are more seeks when creating entries after the first 51, so the creation rate slows down at that point noticeably.  I am able to create 257 directories.

I thought I would see how this disk with 257 top-level directories (named `A1` to `A257`) appears under an older ProDOS (2.4.2 in this case.)  As expected when I do a catalog I see `A1` through `A51` only.  The other directories are still accessible though, if you know what they are called.  For example `CAT A250` works.

I guess if you use more than 51 root directory entires on a HDD partition for example, that pretty much means never going back to ProDOS <2.5.0.  Is there any chance of filesystem corruption if I make changes to such a disk using 2.4.2 I wonder, or should this be safe?

I gave MR.FIXIT.Y2K a try with the floppy with 257 top-level dirs.  The 'T' test mode says "no errors found".  The 'M' main directory repair mode says the volume has 288 blocks, which is a bit fishy but appears to run successfully.  I then ran 'F' fix mode, as requested by Mr Fixit which says "File count fixed" and "There are 222 unused blocks marked used".  After this only the first 51 entries remain.  I guess that MR.FIXIT.Y2K will need further patching to support this.

Hope this was helpful.
